# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nothing to do here
email: your-email@domain.com
description: >
 Hanya contoh untuk tutorial membuat Web Statis dengan Jekyll.
baseurl: "" 
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: petruknisme
github_username:  aancw

# Build settings
markdown: kramdown
